project:
  type: website
  output-dir: docs
  resources:
    - "*.jpeg"
    - "*.jpg"
    - "*.pdf"

website:
  title: "Emily V. Kerns"
  navbar:
    left:
      - href: index.qmd
        text: Home
      
format:
  html:
    theme: jolla
    css: styles.css
    toc: true
    page-layout: full
    papersize: a4
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
about: 
  template: jolla
  image-shape: round
  image-width: 20em

